spring:
  application:
    name: API_Gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: Welcome-API
          uri: lb://WELCOME-API
          predicates:
            - Path=/welcome
        - id: Greet-API
          uri: lb://GREET-API
          predicates:
            - Path=/greet
server:
  port: 3333
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true